[[main]]
  identifier = "about"
  name = "Acerca"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archivado"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Galleria"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "Picante"
  url = "gallery/mine"

[[main]]
  identifier = "posts"
  name = "Entradas"
  url = "posts"
  weight = 4