[[main]]
  identifier = "proj"
  name = "Projects"
  url = "projects"
  weight = 8

[[main]]
  identifier = "kbase"
  name = "KBase"
  url = "development"
  weight = 9
  
[[main]]
  identifier = "templates"
  name = "Templates"
  url = "templates"
  weight = 10

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 29

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 30
